// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web_Form.Data;

#nullable disable

namespace Web_Form.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241215052400_ChangeFormIdToGuid")]
    public partial class ChangeFormIdToGuid : Migration
    {
    }


}
